### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by paulgb** [paulgb/sklearn-pandas#12]
http://stackoverflow.com/questions/24583249/typeerror-fit-takes-exactly-3-arguments-2-given-with-sklearn-and-sklearn-pa#

**Comment by dukebody** [comment]
@paulgb  check https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/base.py#L406. I think you can assume that all transformers accept an `y` argument, defaulting to None and don't use it if not passed.

**Comment by dukebody** [comment]
Thinking it further I don't believe this is really a bug. the `DataFrameMapper` is not intended to be used as a pipeline. That is, one shouldn't pass a model estimator like `KNeighborsClassifier` as a transformer in the mapper.
