### ISSUE TITLE
There is no way to use multiple pre-processors in the same column

### ISSUE THREAD

**Issue by perone** [paulgb/sklearn-pandas#17]
It would be nice if I could do this:

    mapper = DataFrameMapper([
        ('COLUMN', [sklearn.preprocessing.LabelEncoder(), sklearn.preprocessing.OneHotEncoder()]),
    ])

**Comment by dukebody** [comment]
Can't you do this using a scikit-learn Pipeline?

**Comment by dukebody** [comment]
I'm working on this.

**Comment by dukebody** [comment]
We are working on this. See https://github.com/paulgb/sklearn-pandas/pull/28#issuecomment-129148818

**Comment by CodeKiller48** [comment]
How's going on this issue? Do you have a solution to fix the following problem?
mapper = DataFrameMapper([
    ('COLUMN', [sklearn.preprocessing.LabelEncoder(), sklearn.preprocessing.OneHotEncoder()]),
])

**Comment by dukebody** [comment]
It's already fixed, see the merged PR.

**Comment by CodeKiller48** [comment]
Thanks for the response. would you mind forwarding me the link or giving me an example on the usage ?
Really appreciate your help.

**Comment by dukebody** [comment]
@CodeKiller48 Read The Fine Manual: https://github.com/paulgb/sklearn-pandas/blob/master/README.rst#multiple-transformers-for-the-same-column
