### ISSUE TITLE
What should we do for columns that don't need any transformation, but need to be kept?

### ISSUE THREAD

**Issue by caterpillars** [paulgb/sklearn-pandas#19]
Hi,

I am new to this package. I think it is very useful. But I have a bunch of columns where I don't need to do any transformation. But it seems like if we don't keep them into the list, it will be dropped after transformation. In this case, we should we do? separate the columns into two groups, one to transform, one not to, and merge them afterwards? If so, do we know for sure the order is preserved?

Thanks,

Hongli

**Comment by dukebody** [comment]
I think you can use None as transformer.

**Comment by jmizgajski** [comment]
Yes this is it, but it *should* be in the doc - otherwise these features
are not passed to the classifier (one would expect otherwise).

2015-03-04 17:21 GMT+01:00 Israel Saeta Pérez <notifications@github.com>:

**Comment by dukebody** [comment]
Are you up for submitting a pull request? :)

**Comment by dukebody** [comment]
This is already documented. Would you please @calpaterson close this issue (or give me permissions to do so)?
