### ISSUE TITLE
Does this work with Imputer?

### ISSUE THREAD

**Issue by caterpillars** [paulgb/sklearn-pandas#20]
Since Imputer act on all columns, I think. Is the solution to use a pipeline?

Thanks,

Hongli

**Comment by dukebody** [comment]
I've used it with a single column and it works. I guess it works for `axis=0`. If you need inputation working on more columns, then yes, use a pipeline.

Please close this issue if it works for you too, or submit a failing example.

**Comment by dukebody** [comment]
This works with Imputer. You can use it like `(['column_name'], Imputer())` since `Imputer` expects a 2-dimensional array with `[n_samples, n_columns]` as input and `('column_name', Imputer())` would return a 1-dimensional array.

@calpaterson can you close this issue?
