### ISSUE TITLE
PyPi package is out-of-date

### ISSUE THREAD

**Issue by helger** [paulgb/sklearn-pandas#23]
I'm not sure if this is the correct place for this issue. However, the `sklearn-pandas` package on [PyPi](https://pypi.python.org/pypi/sklearn-pandas) is out-of-date and contains some bugs that has since been fixed.

**Comment by dukebody** [comment]
@calpaterson ^^

**Comment by calpaterson** [comment]
I plan to do some kind of release this bank holiday weekend

**Comment by calpaterson** [comment]
I've released version 0.0.10 to PyPI, which includes a fix for unicode.  Thanks for your patience

**Comment by helger** [comment]
Thanks!
