### ISSUE TITLE
Support for xray?

### ISSUE THREAD

**Issue by naught101** [paulgb/sklearn-pandas#40]
[Xray](https://github.com/xray/xray/) does basically a similar job to pandas, but in arbitrary dimensions. It would be great to have something like sklearn-pandas for xray as well.

xray objects already have a `.to_dataframe()` method, which could perhaps be used to do this, but I'm not sure about how it would work translating the results back into n-dimensions.

**Comment by dukebody** [comment]
I'm not sure that functionality would fit the purpose of this package. Can you use Xray with scikit-learn?

**Comment by naught101** [comment]
No. On second thoughts, it's probably better to just use `.to_dataframe()` manually, and just use the pandas DF with scikit-learn.
