### ISSUE TITLE
Help :(  Fail to import sklearn-pandas @Windows 7

### ISSUE THREAD

**Issue by DataTerminatorX** [paulgb/sklearn-pandas#49]
I've already successfully installed sklearn-pandas using "pip install scikitlearn-pandas" on windows's command line.

However, when I try  "import sklearn-pandas", it reports error information as " Cannot import name _name_estimators". I've repeated uninstall and install many times but didn't work.

The whole error information is as below:

  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\sklearn_pandas\__init__.py", line 3, in <m
odule>
    from .dataframe_mapper import DataFrameMapper  # NOQA
  File "C:\Python27\lib\site-packages\sklearn_pandas\dataframe_mapper.py", line
8, in <module>
    from .pipeline import make_transformer_pipeline
  File "C:\Python27\lib\site-packages\sklearn_pandas\pipeline.py", line 2, in <m
odule>
    from sklearn.pipeline import _name_estimators, Pipeline
ImportError: cannot import name _name_estimators

BTW, I've already pre-installed scikit-learn and pandas.

Many thx to anyone who could give me a hand

**Comment by dukebody** [comment]
Which version of `scikit-learn` are you using? Please post the output of the following command: `pip freeze`.

**Comment by DataTerminatorX** [comment]
thx a lot for offering help!

versions are:
scikit-learn  0.14.1
pandas  0.17.0

**Comment by DataTerminatorX** [comment]
I've solved it by updating scikit-learn and pandas. thx a lot !

**Comment by dukebody** [comment]
Great! We have to update docs to state which scikit-learn version is required.

**Comment by dukebody** [comment]
According to my research, `_name_estimators` is present in `scikit-learn>=0.15.0`.

**Comment by dukebody** [comment]
Finally I opted for simply updating `scikit-learn` requirements in the package `setup.py`.
