### ISSUE TITLE
Is there a way to passtrough columns without explicitely marking them?

### ISSUE THREAD

**Issue by lizsz** [paulgb/sklearn-pandas#55]
I.e. let's say the data frame has 200 columns (or 2000 :) ) 
I need to transform a small fraction of these, let's say 20 or 50. I would need to add all columns to a mapper and mark them as none for them to stay in a game. Whereas I think the opposite behavior is more intuitive and more in line with a general philosophy of scikit... (and are more useful in my opinion). In this scenario all columns by default are sent to the output. Those that have transformers are transformed. Those that marked as None (or anything else)-  are dropped.

**Comment by dukebody** [comment]
You can always script that. Something along:

```
transformations = [(col1, transformer1), (col2, transformer2)]
with_transformation = {col for col, transformer in transformations}
keep_equal = [(column, None) for column df.columns if column not in with_transformation]
feats = transformations + keep_equal
mapper = DataFrameMapper(feats)
```

I agree we can have a `non_present='passthrough'` attribute for the `DataFrameMapper` to pass all columns not explicitly named in the mapper untouched. But I wouldn't make it default since it would probably break current code using `sklearn-pandas`.

**Comment by lizsz** [comment]
Just to have a default transformer attached to the mapper would probably be sufficient (and elegant, I think). Having two available ones, PassThroughTransformer, and DropFeatureTransformer would solve it for any case. It would also have a benefit of a possibility to add a default transformer - for example, for SVM a scaler is usually needed. So instead of attaching it to every column, it can be added as a default one, and would be applied to every column

**Comment by dukebody** [comment]
Your proposal of a default transformer sounds interesting! :) I will think about it.

**Comment by dukebody** [comment]
I'm hesitant about what's the best way to implement this. There are some cases where what should happen isn't clear to me. For example, if we have a default transformer and a column appears in a list of features?

DataFrameMapper([(['A', 'B', 'C'], MyTransformer())], default=AnotherTransformer())

Should AnotherTransformer be applied only to columns other than A, B, C?

Another question: Should the default transformer be applied to the non-explicit columns in a row-fashion or column-fashion (i.e. selecting with [] or without)? For some transformers it would be enough to apply them to all the columns together (for example a scaler), but for others like LabelEncoder one needs to apply it to every column separately.

Perhaps trying to solve *every* case is too difficult and we can just aim to solve simple cases like:

- If `default=False`, drop any columns not appearing in any selector.
- If `default=None`, passthrough any columns not appearing in any selector unchanged.
- If `default=Transformer()`, add a feature transformation of the form `(['all', 'previously', 'unselected', features'], Transformer())`.

More complex cases should be handled manually with custom user code.

Doest this sound reasonable? :)

**Comment by lizsz** [comment]
I would say that if user has specified a transformer, than it should be applied. If user wants AnotherTransformer to be applied as well it can be explicitly chained. I see defaultTransformer as a way to apply it to a large number of columns without the need to specify each one. If the user has a limited number of columns that require some special handling (no transformer at all, for example), or some other MyTransformer, than let it be :)

I think simple case is a big step forward. It probably covers majority of use-cases. If there are any additional special corner cases that user wants to be considered let him/her to put a request and then decide

Probably there should be a flag to select row-wise or column wise. However, Scaler is probably internally applied column-wise anyway. So I'd say make column-wise default, and then let user to select row-wise, if required (scaling to a global mean, for example, or for the performance reasons)

**Comment by dukebody** [comment]
Hey @lizsz I drafted an implementation in the PR above. Could you check it and tell me what you think? Thanks!

**Comment by lizsz** [comment]
it looks good.
