### ISSUE TITLE
pip using deprecated-cv branch instead of master

### ISSUE THREAD

**Issue by joshmorel** [paulgb/sklearn-pandas#65]
Hi,

It seems that pip is using deprecated-cv branch instead of master branch.

I noticed this after getting an error when running this code as per README.

```python
>>> mapper4 = DataFrameMapper([
...     ('pet', sklearn.preprocessing.LabelBinarizer()),
...     ('children', None)
... ], default=sklearn.preprocessing.StandardScaler())
>>> np.round(mapper4.fit_transform(data.copy()), 1)
```

Not sure if this is intended, or...?

**Comment by dukebody** [comment]
We've just made a release today: https://pypi.python.org/pypi?:action=display&name=sklearn-pandas&version=1.2.0

Sorry for the delay.
