### ISSUE TITLE
Analogy function to pandas.get_dummies?

### ISSUE THREAD

**Issue by Yevgnen** [paulgb/sklearn-pandas#75]
Hi, thanks for the great library.

I deal with the string categorical values quite often and usually want to transform them into one-hot-encoding. To do so, one may use

1.  `pandas.get_dummies`
2. `sklearn.feature_extraction.DictVectorizer`
3. `sklearn.preprocessing.LabelBinarizer` followed by sklearn.preprocessing.OneHotEncoder

We can see that 1. is useful when one wants to generate the columns name automatically, while it can't handle unseen value of the category quite well automatically. 2. and 3. are opposite, easily to put unseen value a vector of (0, ..., 0) but `*.transform` but lose the column name, and one will usually use the `pandas.to_dict` function to generate a dict input for `sklearn.feature_extraction.DictVectorizer`, the order of the column is usually changed.

So I wonder is there a easy `sklearn-pandas` way to handle this? Thanks in advance.

**Comment by Yevgnen** [comment]
I think a mapper with `sklearn.preprocessing.LabelBinarizer` and `df_out=True` is already the solution that handle columns and unseen value. Sorry for disturbing.

**Comment by dukebody** [comment]
No worries! Thanks for contributing with your comments. :)
