### ISSUE TITLE
DataFrameMapper has no arg 'input_df'

### ISSUE THREAD

**Issue by dreyco676** [paulgb/sklearn-pandas#94]
Not sure if the documentation is old but I can't seem to use the `input_df` argument.

`mapper_df = DataFrameMapper([('TextColumn', CountVectorizer(min_df=4))], input_df=True, df_out=True)`

**Comment by keithgw** [comment]
same sklearn-pandas==1.3.0

**Comment by dukebody** [comment]
Sorry, `input_df` is a feature that was not released yet. A new version of `sklearn-pandas` including this feature has been released today: https://pypi.python.org/pypi/sklearn-pandas

If you still have issues, please reopen this ticket.
